packages:
    - ./packages/*
    - ./plugins/*
    - ./tests/*
    - ./templates/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    core-js: true
    esbuild: false

catalogs:
    dep:
        # core
        ts-vista: ~0.2.3
        # ammolite
        "@ammolite/integration": ~0.1.4
        "@ammolite/rsbuild": ~0.1.4
        "@ammolite/postcss": ~0.1.4
        ammolite: ~0.1.4
        # rspack
        "@rsbuild/core": ^1.7.0
        "@rslib/core": ~0.23.0
        # vite
        vitest: ^4.1.9
        vite-tsconfig-paths: ^6.1.0
        # react
        "@types/react": ^19.2.17
        "@types/react-dom": ^19.2.0
        react: ^19.2.7
        react-dom: ^19.2.7
    dev:
        # rsbuild
        "@rspack/core": 1.7.0
        "@rsbuild/core": 1.7.0
        # postcss
        postcss: 8.5.0
    peer:
        # rsbuild
        "@rspack/core": ^1.7.0 || ^2.0.0
        "@rsbuild/core": ^1.7.0 || ^2.0.0
        # postcss
        postcss: ^8.5.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    # config
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    # tsdown
    - "@tsdown/*"
    - "tsdown"
    # core
    - "ts-vista"
    # ammolite
    - "@ammolite/compiler"
    - "@ammolite/integration"
    - "@ammolite/unplugin"
    - "@ammolite/rsbuild"
    - "@ammolite/postcss"
    - "ammolite"
